import pandas
a = [1,2]
b = [3,4]
print a+b

pass

# Loading data into the 2 dataframes
sanfran_df = pandas.DataFrame.from_csv("/Users/ralphblanes/PycharmProjects/Data-Science-Projects/Crime Visualizations/sanfrancisco_incidents_summer_2014.csv")


prostitutabase = sanfran_df[sanfran_df['Category']=='PROSTITUTION']
print prostitutabase.head()

prostituctionary = {}
keys = sanfran_df['DayOfWeek'].unique()
for key in keys:
     prostituctionary[key] = 0

for row in prostitutabase.iterrows():
    #Counting crimes per region
    if row[1][2] in prostituctionary.keys():
        prostituctionary[row[1][2]] = prostituctionary[row[1][2]] + 1

print "Days of week and prostitution"
print prostituctionary

crime_count_dict = {}

for key in keys:
    crime_count_dict[key] = 0
# Counting all types of incidents
crime_count_dict = {}
region_count_dict = {}
keys = sanfran_df['Category'].unique()
for key in keys:
    crime_count_dict[key] = 0

for i,key in enumerate(sanfran_df['PdDistrict'].unique()):
    region_count_dict[key] = {'KIDNAPPING': 0, 'WEAPON LAWS': 0, 'SECONDARY CODES': 0, 'WARRANTS': 0, 'LOITERING': 0, 'EMBEZZLEMENT': 0, 'PORNOGRAPHY/OBSCENE MAT': 0, 'SUICIDE': 0, 'DRIVING UNDER THE INFLUENCE': 0, 'ROBBERY': 0, 'BURGLARY': 0, 'SUSPICIOUS OCC': 0, 'ARSON': 0, 'BRIBERY': 0, 'FORGERY/COUNTERFEITING': 0, 'DRUNKENNESS': 0, 'GAMBLING': 0, 'OTHER OFFENSES': 0, 'FRAUD': 0, 'FAMILY OFFENSES': 0, 'DRUG/NARCOTIC': 0, 'TRESPASS': 0, 'LARCENY/THEFT': 0, 'VANDALISM': 0, 'NON-CRIMINAL': 0, 'EXTORTION': 0, 'LIQUOR LAWS': 0, 'VEHICLE THEFT': 0, 'STOLEN PROPERTY': 0, 'ASSAULT': 0, 'RUNAWAY': 0, 'MISSING PERSON': 0, 'DISORDERLY CONDUCT': 0, 'PROSTITUTION': 0}

#Counting the distribution of different types of crimes
for key in crime_count_dict.keys():
    for row in sanfran_df.iterrows():
        if row[1][0] == key:
            crime_count_dict[key] += 1


for row in sanfran_df.iterrows():
     #Counting crimes per region
        if row[1][5] in region_count_dict.keys():
            cur_region = row[1][5]
            cur_crime = row[1][0]
            region_dict = region_count_dict[cur_region]
            region_vals = region_count_dict[cur_region][cur_crime]
            region_count_dict[cur_region][cur_crime] = region_count_dict[cur_region][cur_crime] + 1

print crime_count_dict
print("Regions")
for key in region_count_dict.keys():
    print key
    print(region_count_dict[key])



PARK = {'KIDNAPPING': 3, 'WEAPON LAWS': 11, 'VANDALISM': 1, 'ARSON': 1, 'SECONDARY CODES': 12, 'WARRANTS': 109, 'LOITERING': 0, 'DRUG/NARCOTIC': 63, 'EMBEZZLEMENT': 0, 'TRESPASS': 6, 'SUICIDE': 1, 'DRIVING UNDER THE INFLUENCE': 4, 'LARCENY/THEFT': 576, 'ROBBERY': 13, 'NON-CRIMINAL': 193, 'BURGLARY': 0, 'STOLEN PROPERTY': 1, 'EXTORTION': 0, 'PORNOGRAPHY/OBSCENE MAT': 0, 'MISSING PERSON': 141, 'LIQUOR LAWS': 2, 'FAMILY OFFENSES': 0, 'ASSAULT': 118, 'VEHICLE THEFT': 150, 'FORGERY/COUNTERFEITING': 0, 'PROSTITUTION': 0, 'BRIBERY': 0, 'SUSPICIOUS OCC': 60, 'FRAUD': 12, 'GAMBLING': 0, 'DISORDERLY CONDUCT': 5, 'OTHER OFFENSES': 197, 'RUNAWAY': 5, 'DRUNKENNESS': 9}
BAYVIEW = {'KIDNAPPING': 21, 'WEAPON LAWS': 79, 'VANDALISM': 5, 'ARSON': 11, 'SECONDARY CODES': 76, 'WARRANTS': 249, 'LOITERING': 1, 'DRUG/NARCOTIC': 111, 'EMBEZZLEMENT': 3, 'TRESPASS': 33, 'SUICIDE': 2, 'DRIVING UNDER THE INFLUENCE': 15, 'LARCENY/THEFT': 481, 'ROBBERY': 36, 'NON-CRIMINAL': 203, 'BURGLARY': 0, 'STOLEN PROPERTY': 1, 'EXTORTION': 0, 'PORNOGRAPHY/OBSCENE MAT': 0, 'MISSING PERSON': 141, 'LIQUOR LAWS': 5, 'FAMILY OFFENSES': 0, 'ASSAULT': 359, 'VEHICLE THEFT': 245, 'FORGERY/COUNTERFEITING': 0, 'PROSTITUTION': 1, 'BRIBERY': 0, 'SUSPICIOUS OCC': 171, 'FRAUD': 22, 'GAMBLING': 0, 'DISORDERLY CONDUCT': 3, 'OTHER OFFENSES': 435, 'RUNAWAY': 7, 'DRUNKENNESS': 9}
TARAVAL = {'KIDNAPPING': 7, 'WEAPON LAWS': 14, 'VANDALISM': 1, 'ARSON': 2, 'SECONDARY CODES': 36, 'WARRANTS': 65, 'LOITERING': 0, 'DRUG/NARCOTIC': 31, 'EMBEZZLEMENT': 1, 'TRESPASS': 10, 'SUICIDE': 1, 'DRIVING UNDER THE INFLUENCE': 8, 'LARCENY/THEFT': 547, 'ROBBERY': 21, 'NON-CRIMINAL': 210, 'BURGLARY': 2, 'STOLEN PROPERTY': 0, 'EXTORTION': 1, 'PORNOGRAPHY/OBSCENE MAT': 1, 'MISSING PERSON': 107, 'LIQUOR LAWS': 4, 'FAMILY OFFENSES': 0, 'ASSAULT': 147, 'VEHICLE THEFT': 222, 'FORGERY/COUNTERFEITING': 2, 'PROSTITUTION': 2, 'BRIBERY': 0, 'SUSPICIOUS OCC': 104, 'FRAUD': 17, 'GAMBLING': 0, 'DISORDERLY CONDUCT': 0, 'OTHER OFFENSES': 269, 'RUNAWAY': 16, 'DRUNKENNESS': 5}
RICHMOND = {'KIDNAPPING': 4, 'WEAPON LAWS': 10, 'VANDALISM': 0, 'ARSON': 1, 'SECONDARY CODES': 25, 'WARRANTS': 45, 'LOITERING': 0, 'DRUG/NARCOTIC': 51, 'EMBEZZLEMENT': 0, 'TRESPASS': 9, 'SUICIDE': 1, 'DRIVING UNDER THE INFLUENCE': 21, 'LARCENY/THEFT': 527, 'ROBBERY': 9, 'NON-CRIMINAL': 250, 'BURGLARY': 0, 'STOLEN PROPERTY': 0, 'EXTORTION': 0, 'PORNOGRAPHY/OBSCENE MAT': 0, 'MISSING PERSON': 50, 'LIQUOR LAWS': 2, 'FAMILY OFFENSES': 0, 'ASSAULT': 81, 'VEHICLE THEFT': 118, 'FORGERY/COUNTERFEITING': 0, 'PROSTITUTION': 0, 'BRIBERY': 0, 'SUSPICIOUS OCC': 89, 'FRAUD': 15, 'GAMBLING': 0, 'DISORDERLY CONDUCT': 0, 'OTHER OFFENSES': 234, 'RUNAWAY': 2, 'DRUNKENNESS': 2}
TENDERLOIN = {'KIDNAPPING': 7, 'WEAPON LAWS': 30, 'VANDALISM': 1, 'ARSON': 0, 'SECONDARY CODES': 37, 'WARRANTS': 237, 'LOITERING': 1, 'DRUG/NARCOTIC': 284, 'EMBEZZLEMENT': 1, 'TRESPASS': 22, 'SUICIDE': 0, 'DRIVING UNDER THE INFLUENCE': 2, 'LARCENY/THEFT': 481, 'ROBBERY': 37, 'NON-CRIMINAL': 216, 'BURGLARY': 1, 'STOLEN PROPERTY': 0, 'EXTORTION': 0, 'PORNOGRAPHY/OBSCENE MAT': 0, 'MISSING PERSON': 53, 'LIQUOR LAWS': 5, 'FAMILY OFFENSES': 0, 'ASSAULT': 324, 'VEHICLE THEFT': 34, 'FORGERY/COUNTERFEITING': 1, 'PROSTITUTION': 8, 'BRIBERY': 0, 'SUSPICIOUS OCC': 125, 'FRAUD': 19, 'GAMBLING': 0, 'DISORDERLY CONDUCT': 2, 'OTHER OFFENSES': 316, 'RUNAWAY': 0, 'DRUNKENNESS': 13}
MISSION = {'KIDNAPPING': 15, 'WEAPON LAWS': 74, 'VANDALISM': 1, 'ARSON': 11, 'SECONDARY CODES': 77, 'WARRANTS': 281, 'LOITERING': 0, 'DRUG/NARCOTIC': 217, 'EMBEZZLEMENT': 0, 'TRESPASS': 59, 'SUICIDE': 4, 'DRIVING UNDER THE INFLUENCE': 11, 'LARCENY/THEFT': 671, 'ROBBERY': 42, 'NON-CRIMINAL': 345, 'BURGLARY': 2, 'STOLEN PROPERTY': 3, 'EXTORTION': 3, 'PORNOGRAPHY/OBSCENE MAT': 0, 'MISSING PERSON': 297, 'LIQUOR LAWS': 3, 'FAMILY OFFENSES': 8, 'ASSAULT': 459, 'VEHICLE THEFT': 306, 'FORGERY/COUNTERFEITING': 3, 'PROSTITUTION': 23, 'BRIBERY': 0, 'SUSPICIOUS OCC': 165, 'FRAUD': 49, 'GAMBLING': 1, 'DISORDERLY CONDUCT': 12, 'OTHER OFFENSES': 502, 'RUNAWAY': 19, 'DRUNKENNESS': 37}
SOUTHERN = {'KIDNAPPING': 17, 'WEAPON LAWS': 44, 'VANDALISM': 4, 'ARSON': 22, 'SECONDARY CODES': 63, 'WARRANTS': 331, 'LOITERING': 0, 'DRUG/NARCOTIC': 242, 'EMBEZZLEMENT': 2, 'TRESPASS': 45, 'SUICIDE': 2, 'DRIVING UNDER THE INFLUENCE': 18, 'LARCENY/THEFT': 2562, 'ROBBERY': 37, 'NON-CRIMINAL': 639, 'BURGLARY': 0, 'STOLEN PROPERTY': 2, 'EXTORTION': 1, 'PORNOGRAPHY/OBSCENE MAT': 0, 'MISSING PERSON': 159, 'LIQUOR LAWS': 12, 'FAMILY OFFENSES': 1, 'ASSAULT': 528, 'VEHICLE THEFT': 161, 'FORGERY/COUNTERFEITING': 5, 'PROSTITUTION': 7, 'BRIBERY': 0, 'SUSPICIOUS OCC': 213, 'FRAUD': 42, 'GAMBLING': 0, 'DISORDERLY CONDUCT': 3, 'OTHER OFFENSES': 543, 'RUNAWAY': 3, 'DRUNKENNESS': 31}
INGLESIDE = {'KIDNAPPING': 22, 'WEAPON LAWS': 28, 'VANDALISM': 0, 'ARSON': 5, 'SECONDARY CODES': 45, 'WARRANTS': 110, 'LOITERING': 0, 'DRUG/NARCOTIC': 81, 'EMBEZZLEMENT': 0, 'TRESPASS': 9, 'SUICIDE': 2, 'DRIVING UNDER THE INFLUENCE': 7, 'LARCENY/THEFT': 548, 'ROBBERY': 44, 'NON-CRIMINAL': 189, 'BURGLARY': 0, 'STOLEN PROPERTY': 1, 'EXTORTION': 1, 'PORNOGRAPHY/OBSCENE MAT': 0, 'MISSING PERSON': 131, 'LIQUOR LAWS': 2, 'FAMILY OFFENSES': 1, 'ASSAULT': 292, 'VEHICLE THEFT': 382, 'FORGERY/COUNTERFEITING': 0, 'PROSTITUTION': 1, 'BRIBERY': 1, 'SUSPICIOUS OCC': 93, 'FRAUD': 13, 'GAMBLING': 0, 'DISORDERLY CONDUCT': 4, 'OTHER OFFENSES': 351, 'RUNAWAY': 6, 'DRUNKENNESS': 9}
NORTHERN = {'KIDNAPPING': 8, 'WEAPON LAWS': 48, 'VANDALISM': 2, 'ARSON': 9, 'SECONDARY CODES': 42, 'WARRANTS': 193, 'LOITERING': 0, 'DRUG/NARCOTIC': 174, 'EMBEZZLEMENT': 1, 'TRESPASS': 36, 'SUICIDE': 1, 'DRIVING UNDER THE INFLUENCE': 8, 'LARCENY/THEFT': 1499, 'ROBBERY': 30, 'NON-CRIMINAL': 347, 'BURGLARY': 1, 'STOLEN PROPERTY': 0, 'EXTORTION': 1, 'PORNOGRAPHY/OBSCENE MAT': 0, 'MISSING PERSON': 101, 'LIQUOR LAWS': 5, 'FAMILY OFFENSES': 0, 'ASSAULT': 297, 'VEHICLE THEFT': 202, 'FORGERY/COUNTERFEITING': 4, 'PROSTITUTION': 3, 'BRIBERY': 0, 'SUSPICIOUS OCC': 149, 'FRAUD': 23, 'GAMBLING': 0, 'DISORDERLY CONDUCT': 1, 'OTHER OFFENSES': 394, 'RUNAWAY': 2, 'DRUNKENNESS': 8}
CENTRAL = {'KIDNAPPING': 13, 'WEAPON LAWS': 16, 'VANDALISM': 2, 'ARSON': 1, 'SECONDARY CODES': 29, 'WARRANTS': 162, 'LOITERING': 1, 'DRUG/NARCOTIC': 91, 'EMBEZZLEMENT': 2, 'TRESPASS': 52, 'SUICIDE': 0, 'DRIVING UNDER THE INFLUENCE': 6, 'LARCENY/THEFT': 1574, 'ROBBERY': 39, 'NON-CRIMINAL': 431, 'BURGLARY': 0, 'STOLEN PROPERTY': 0, 'EXTORTION': 0, 'PORNOGRAPHY/OBSCENE MAT': 0, 'MISSING PERSON': 86, 'LIQUOR LAWS': 2, 'FAMILY OFFENSES': 0, 'ASSAULT': 277, 'VEHICLE THEFT': 146, 'FORGERY/COUNTERFEITING': 3, 'PROSTITUTION': 67, 'BRIBERY': 0, 'SUSPICIOUS OCC': 131, 'FRAUD': 30, 'GAMBLING': 0, 'DISORDERLY CONDUCT': 1, 'OTHER OFFENSES': 326, 'RUNAWAY': 1, 'DRUNKENNESS': 24}
TOTAL = {'KIDNAPPING': 117, 'WEAPON LAWS': 354, 'SECONDARY CODES': 442, 'WARRANTS': 1782, 'LOITERING': 3, 'EMBEZZLEMENT': 10, 'PORNOGRAPHY/OBSCENE MAT': 1, 'SUICIDE': 14, 'DRIVING UNDER THE INFLUENCE': 100, 'ROBBERY': 308, 'BURGLARY': 6, 'SUSPICIOUS OCC': 1300, 'ARSON': 63, 'BRIBERY': 1, 'FORGERY/COUNTERFEITING': 18, 'DRUNKENNESS': 147, 'GAMBLING': 1, 'OTHER OFFENSES': 3567, 'FRAUD': 242, 'FAMILY OFFENSES': 10, 'DRUG/NARCOTIC': 1345, 'TRESPASS': 281, 'LARCENY/THEFT': 9466, 'VANDALISM': 17, 'NON-CRIMINAL': 3023, 'EXTORTION': 7, 'LIQUOR LAWS': 42, 'VEHICLE THEFT': 1966, 'STOLEN PROPERTY': 8, 'ASSAULT': 2882, 'RUNAWAY': 61, 'MISSING PERSON': 1266, 'DISORDERLY CONDUCT': 31, 'PROSTITUTION': 112}


all_list = [PARK,BAYVIEW,TARAVAL,RICHMOND,TENDERLOIN,MISSION,SOUTHERN,INGLESIDE,NORTHERN,CENTRAL,TOTAL]



for member in all_list:
    print sum(member.values())
# Creating a plot with the types of incidents


# Different types of crimes should have different symbols



# Maybe show subcategory findings (i.e different types of asaults)


